artifact_location: file:///C:/Users/Tough/OneDrive/Desktop/Tough/MLOPS/ML_Flow/My_Class_Workings/MlFlow_Starter/410372016129441185
creation_time: 1738424732517
experiment_id: '410372016129441185'
last_update_time: 1738424732517
lifecycle_stage: active
name: MLFLOW Quickstart
